// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ivr8-yni1c9k2swof.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Ivr8
{

    [global::ProtoBuf.ProtoContract()]
    public partial class InternalDimension : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public eMeasurementUnit measurementUnit { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0)]
        public float slackMax
        {
            get { return __pbn__slackMax ?? 0; }
            set { __pbn__slackMax = value; }
        }
        public bool ShouldSerializeslackMax() => __pbn__slackMax != null;
        public void ResetslackMax() => __pbn__slackMax = null;
        private float? __pbn__slackMax;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0)]
        public float tardyMax
        {
            get { return __pbn__tardyMax ?? 0; }
            set { __pbn__tardyMax = value; }
        }
        public bool ShouldSerializetardyMax() => __pbn__tardyMax != null;
        public void ResettardyMax() => __pbn__tardyMax = null;
        private float? __pbn__tardyMax;

        [global::ProtoBuf.ProtoContract()]
        public enum eMeasurementUnit
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SECONDS")]
            Seconds = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MINUTES")]
            Minutes = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"HOURS")]
            Hours = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"DAYS")]
            Days = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"KILOMETRES")]
            Kilometres = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"MILES")]
            Miles = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CapacityDimension : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"units", IsRequired = true)]
        public string Units { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0)]
        public float slackMax
        {
            get { return __pbn__slackMax ?? 0; }
            set { __pbn__slackMax = value; }
        }
        public bool ShouldSerializeslackMax() => __pbn__slackMax != null;
        public void ResetslackMax() => __pbn__slackMax = null;
        private float? __pbn__slackMax;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0)]
        public float tardyMax
        {
            get { return __pbn__tardyMax ?? 0; }
            set { __pbn__tardyMax = value; }
        }
        public bool ShouldSerializetardyMax() => __pbn__tardyMax != null;
        public void ResettardyMax() => __pbn__tardyMax = null;
        private float? __pbn__tardyMax;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DimensionConfiguration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public InternalDimension timeConfig { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public InternalDimension distanceConfig { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<CapacityDimension> capacityDimensions { get; } = new global::System.Collections.Generic.List<CapacityDimension>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Geocode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"longitude", IsRequired = true)]
        public float Longitude { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"latitude", IsRequired = true)]
        public float Latitude { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Window : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start", IsRequired = true)]
        public float Start { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end", IsRequired = true)]
        public float End { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0)]
        public float slackCostCoef
        {
            get { return __pbn__slackCostCoef ?? 0; }
            set { __pbn__slackCostCoef = value; }
        }
        public bool ShouldSerializeslackCostCoef() => __pbn__slackCostCoef != null;
        public void ResetslackCostCoef() => __pbn__slackCostCoef = null;
        private float? __pbn__slackCostCoef;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0)]
        public float tardyCostCoef
        {
            get { return __pbn__tardyCostCoef ?? 0; }
            set { __pbn__tardyCostCoef = value; }
        }
        public bool ShouldSerializetardyCostCoef() => __pbn__tardyCostCoef != null;
        public void ResettardyCostCoef() => __pbn__tardyCostCoef = null;
        private float? __pbn__tardyCostCoef;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public float slackMax
        {
            get { return __pbn__slackMax ?? -1; }
            set { __pbn__slackMax = value; }
        }
        public bool ShouldSerializeslackMax() => __pbn__slackMax != null;
        public void ResetslackMax() => __pbn__slackMax = null;
        private float? __pbn__slackMax;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public float tardyMax
        {
            get { return __pbn__tardyMax ?? -1; }
            set { __pbn__tardyMax = value; }
        }
        public bool ShouldSerializetardyMax() => __pbn__tardyMax != null;
        public void ResettardyMax() => __pbn__tardyMax = null;
        private float? __pbn__tardyMax;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Location : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"geocode")]
        public Geocode Geocode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
        public global::System.Collections.Generic.List<Attribute> Attributes { get; } = new global::System.Collections.Generic.List<Attribute>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Attribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimensionId { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string vehicleId
            {
                get { return __pbn__vehicleId ?? ""; }
                set { __pbn__vehicleId = value; }
            }
            public bool ShouldSerializevehicleId() => __pbn__vehicleId != null;
            public void ResetvehicleId() => __pbn__vehicleId = null;
            private string __pbn__vehicleId;

            [global::ProtoBuf.ProtoMember(3, Name = @"quantity")]
            public float Quantity
            {
                get { return __pbn__Quantity.GetValueOrDefault(); }
                set { __pbn__Quantity = value; }
            }
            public bool ShouldSerializeQuantity() => __pbn__Quantity != null;
            public void ResetQuantity() => __pbn__Quantity = null;
            private float? __pbn__Quantity;

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<Window> arrivalWindows { get; } = new global::System.Collections.Generic.List<Window>();

            [global::ProtoBuf.ProtoMember(5)]
            public global::System.Collections.Generic.List<Window> departureWindows { get; } = new global::System.Collections.Generic.List<Window>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Job : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Task pickupTask { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Task dropoffTask { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"penalty", IsRequired = true)]
        public float Penalty { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public VehicleRelation vehicleRelations { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public CompartmentRelation compartmentRelations { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class VehicleRelation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Type type { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<string> vehicleIds { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoContract()]
            public enum Type
            {
                [global::ProtoBuf.ProtoEnum(Name = @"INCLUSIVE")]
                Inclusive = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"EXCLUSIVE")]
                Exclusive = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CompartmentRelation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Type type { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<string> compartmentIds { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoContract()]
            public enum Type
            {
                [global::ProtoBuf.ProtoEnum(Name = @"INCLUSIVE")]
                Inclusive = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"EXCLUSIVE")]
                Exclusive = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Task : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string taskId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string locationId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
            public global::System.Collections.Generic.List<Attribute> Attributes { get; } = new global::System.Collections.Generic.List<Attribute>();

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<TripConstraint> tripConstraints { get; } = new global::System.Collections.Generic.List<TripConstraint>();

            [global::ProtoBuf.ProtoMember(5, Name = @"predecessors")]
            public TaskRelation Predecessors { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"successors")]
            public TaskRelation Successors { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Attribute : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
                public string dimensionId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"quantity")]
                public float Quantity
                {
                    get { return __pbn__Quantity.GetValueOrDefault(); }
                    set { __pbn__Quantity = value; }
                }
                public bool ShouldSerializeQuantity() => __pbn__Quantity != null;
                public void ResetQuantity() => __pbn__Quantity = null;
                private float? __pbn__Quantity;

                [global::ProtoBuf.ProtoMember(3, Name = @"windows")]
                public global::System.Collections.Generic.List<Window> Windows { get; } = new global::System.Collections.Generic.List<Window>();

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TaskRelation : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
                public Type type { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                public global::System.Collections.Generic.List<string> taskIds { get; } = new global::System.Collections.Generic.List<string>();

                [global::ProtoBuf.ProtoContract()]
                public enum Type
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"INCLUSIVE")]
                    Inclusive = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"EXCLUSIVE")]
                    Exclusive = 1,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum TripConstraint
            {
                [global::ProtoBuf.ProtoEnum(Name = @"FIRST")]
                First = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"LAST")]
                Last = 1,
            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransitSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transits")]
        public global::System.Collections.Generic.List<TransitValue> Transits { get; } = new global::System.Collections.Generic.List<TransitValue>();

        [global::ProtoBuf.ProtoContract()]
        public partial class TransitValue : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string fromId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string toId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"value", IsRequired = true)]
            public float Value { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransitGenerator : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string requestId
        {
            get { return __pbn__requestId ?? ""; }
            set { __pbn__requestId = value; }
        }
        public bool ShouldSerializerequestId() => __pbn__requestId != null;
        public void ResetrequestId() => __pbn__requestId = null;
        private string __pbn__requestId;

        [global::ProtoBuf.ProtoMember(3)]
        public TransitSet transitSet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleClass : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"attributes")]
        public global::System.Collections.Generic.List<Attribute> Attributes { get; } = new global::System.Collections.Generic.List<Attribute>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<string> transitRuleIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string compartmentSetId
        {
            get { return __pbn__compartmentSetId ?? ""; }
            set { __pbn__compartmentSetId = value; }
        }
        public bool ShouldSerializecompartmentSetId() => __pbn__compartmentSetId != null;
        public void ResetcompartmentSetId() => __pbn__compartmentSetId = null;
        private string __pbn__compartmentSetId;

        [global::ProtoBuf.ProtoContract()]
        public partial class Attribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimensionId { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string transitGeneratorId
            {
                get { return __pbn__transitGeneratorId ?? ""; }
                set { __pbn__transitGeneratorId = value; }
            }
            public bool ShouldSerializetransitGeneratorId() => __pbn__transitGeneratorId != null;
            public void ResettransitGeneratorId() => __pbn__transitGeneratorId = null;
            private string __pbn__transitGeneratorId;

            [global::ProtoBuf.ProtoMember(3)]
            public float transitCoef
            {
                get { return __pbn__transitCoef.GetValueOrDefault(); }
                set { __pbn__transitCoef = value; }
            }
            public bool ShouldSerializetransitCoef() => __pbn__transitCoef != null;
            public void ResettransitCoef() => __pbn__transitCoef = null;
            private float? __pbn__transitCoef;

            [global::ProtoBuf.ProtoMember(4)]
            public float taskCoef
            {
                get { return __pbn__taskCoef.GetValueOrDefault(); }
                set { __pbn__taskCoef = value; }
            }
            public bool ShouldSerializetaskCoef() => __pbn__taskCoef != null;
            public void ResettaskCoef() => __pbn__taskCoef = null;
            private float? __pbn__taskCoef;

            [global::ProtoBuf.ProtoMember(5)]
            public float locationCoef
            {
                get { return __pbn__locationCoef.GetValueOrDefault(); }
                set { __pbn__locationCoef = value; }
            }
            public bool ShouldSerializelocationCoef() => __pbn__locationCoef != null;
            public void ResetlocationCoef() => __pbn__locationCoef = null;
            private float? __pbn__locationCoef;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleCostClass : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float fixedCost { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
        public global::System.Collections.Generic.List<Attribute> Attributes { get; } = new global::System.Collections.Generic.List<Attribute>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Attribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimensionId { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public float transitCostCoef
            {
                get { return __pbn__transitCostCoef.GetValueOrDefault(); }
                set { __pbn__transitCostCoef = value; }
            }
            public bool ShouldSerializetransitCostCoef() => __pbn__transitCostCoef != null;
            public void ResettransitCostCoef() => __pbn__transitCostCoef = null;
            private float? __pbn__transitCostCoef;

            [global::ProtoBuf.ProtoMember(3)]
            public float taskCostCoef
            {
                get { return __pbn__taskCostCoef.GetValueOrDefault(); }
                set { __pbn__taskCostCoef = value; }
            }
            public bool ShouldSerializetaskCostCoef() => __pbn__taskCostCoef != null;
            public void ResettaskCostCoef() => __pbn__taskCostCoef = null;
            private float? __pbn__taskCostCoef;

            [global::ProtoBuf.ProtoMember(4)]
            public float locationCostCoef
            {
                get { return __pbn__locationCostCoef.GetValueOrDefault(); }
                set { __pbn__locationCostCoef = value; }
            }
            public bool ShouldSerializelocationCostCoef() => __pbn__locationCostCoef != null;
            public void ResetlocationCostCoef() => __pbn__locationCostCoef = null;
            private float? __pbn__locationCostCoef;

            [global::ProtoBuf.ProtoMember(5)]
            public float slackCostCoef
            {
                get { return __pbn__slackCostCoef.GetValueOrDefault(); }
                set { __pbn__slackCostCoef = value; }
            }
            public bool ShouldSerializeslackCostCoef() => __pbn__slackCostCoef != null;
            public void ResetslackCostCoef() => __pbn__slackCostCoef = null;
            private float? __pbn__slackCostCoef;

            [global::ProtoBuf.ProtoMember(6)]
            public float tardyCostCoef
            {
                get { return __pbn__tardyCostCoef.GetValueOrDefault(); }
                set { __pbn__tardyCostCoef = value; }
            }
            public bool ShouldSerializetardyCostCoef() => __pbn__tardyCostCoef != null;
            public void ResettardyCostCoef() => __pbn__tardyCostCoef = null;
            private float? __pbn__tardyCostCoef;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vehicle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string classId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string costClassId { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public Shift shift { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"capacities")]
        public global::System.Collections.Generic.List<Capacity> Capacities { get; } = new global::System.Collections.Generic.List<Capacity>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<string> transitRuleIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string compartmentSetId
        {
            get { return __pbn__compartmentSetId ?? ""; }
            set { __pbn__compartmentSetId = value; }
        }
        public bool ShouldSerializecompartmentSetId() => __pbn__compartmentSetId != null;
        public void ResetcompartmentSetId() => __pbn__compartmentSetId = null;
        private string __pbn__compartmentSetId;

        [global::ProtoBuf.ProtoContract()]
        public partial class Task : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string locationId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"attributes")]
            public global::System.Collections.Generic.List<Attribute> Attributes { get; } = new global::System.Collections.Generic.List<Attribute>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Attribute : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
                public string dimensionId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"quantity")]
                public float Quantity
                {
                    get { return __pbn__Quantity.GetValueOrDefault(); }
                    set { __pbn__Quantity = value; }
                }
                public bool ShouldSerializeQuantity() => __pbn__Quantity != null;
                public void ResetQuantity() => __pbn__Quantity = null;
                private float? __pbn__Quantity;

                [global::ProtoBuf.ProtoMember(3, Name = @"windows")]
                public global::System.Collections.Generic.List<Window> Windows { get; } = new global::System.Collections.Generic.List<Window>();

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Shift : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Vehicle.Task shiftStart { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public Vehicle.Task shiftEnd { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Capacity : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimensionId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float capacity { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskSequence : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string vehicleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"taskId")]
        public global::System.Collections.Generic.List<string> taskIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"compartmentId")]
        public global::System.Collections.Generic.List<string> compartmentIds { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransitRule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string dimensionId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool useStandingState
        {
            get { return __pbn__useStandingState ?? true; }
            set { __pbn__useStandingState = value; }
        }
        public bool ShouldSerializeuseStandingState() => __pbn__useStandingState != null;
        public void ResetuseStandingState() => __pbn__useStandingState = null;
        private bool? __pbn__useStandingState;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool useTransitState
        {
            get { return __pbn__useTransitState ?? false; }
            set { __pbn__useTransitState = value; }
        }
        public bool ShouldSerializeuseTransitState() => __pbn__useTransitState != null;
        public void ResetuseTransitState() => __pbn__useTransitState = null;
        private bool? __pbn__useTransitState;

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string ruleIdPrefix { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"triggers")]
        public global::System.Collections.Generic.List<Trigger> Triggers { get; } = new global::System.Collections.Generic.List<Trigger>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Trigger : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
            public float Value { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"quantity", IsRequired = true)]
            public float Quantity { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Compartment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"capacities")]
        public global::System.Collections.Generic.List<Capacity> Capacities { get; } = new global::System.Collections.Generic.List<Capacity>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Capacity : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimensionId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float capacity { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CompartmentSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> compartmentIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<GroupLimit> groupLimits { get; } = new global::System.Collections.Generic.List<GroupLimit>();

        [global::ProtoBuf.ProtoContract()]
        public partial class GroupLimit : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public global::System.Collections.Generic.List<string> compartmentIds { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(2, Name = @"coefficients")]
            public float[] Coefficients { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public string dimensionId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"limit", IsRequired = true)]
            public float Limit { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            [global::System.ComponentModel.DefaultValue(false)]
            public bool checkStandingState
            {
                get { return __pbn__checkStandingState ?? false; }
                set { __pbn__checkStandingState = value; }
            }
            public bool ShouldSerializecheckStandingState() => __pbn__checkStandingState != null;
            public void ResetcheckStandingState() => __pbn__checkStandingState = null;
            private bool? __pbn__checkStandingState;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Model : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dimensions", IsRequired = true)]
        public DimensionConfiguration Dimensions { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"locations")]
        public global::System.Collections.Generic.List<Location> Locations { get; } = new global::System.Collections.Generic.List<Location>();

        [global::ProtoBuf.ProtoMember(3, Name = @"jobs")]
        public global::System.Collections.Generic.List<Job> Jobs { get; } = new global::System.Collections.Generic.List<Job>();

        [global::ProtoBuf.ProtoMember(4, Name = @"vehicles")]
        public global::System.Collections.Generic.List<Vehicle> Vehicles { get; } = new global::System.Collections.Generic.List<Vehicle>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<VehicleClass> vehicleClasses { get; } = new global::System.Collections.Generic.List<VehicleClass>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<VehicleCostClass> vehicleCostClasses { get; } = new global::System.Collections.Generic.List<VehicleCostClass>();

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<TransitRule> transitRules { get; } = new global::System.Collections.Generic.List<TransitRule>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<TransitGenerator> transitGenerators { get; } = new global::System.Collections.Generic.List<TransitGenerator>();

        [global::ProtoBuf.ProtoMember(9, Name = @"taskSequence")]
        public global::System.Collections.Generic.List<TaskSequence> taskSequences { get; } = new global::System.Collections.Generic.List<TaskSequence>();

        [global::ProtoBuf.ProtoMember(10, Name = @"compartments")]
        public global::System.Collections.Generic.List<Compartment> Compartments { get; } = new global::System.Collections.Generic.List<Compartment>();

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<CompartmentSet> compartmentSets { get; } = new global::System.Collections.Generic.List<CompartmentSet>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SolveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"model")]
        public Model Model { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string modelID
        {
            get { return __pbn__modelID ?? ""; }
            set { __pbn__modelID = value; }
        }
        public bool ShouldSerializemodelID() => __pbn__modelID != null;
        public void ResetmodelID() => __pbn__modelID = null;
        private string __pbn__modelID;

        [global::ProtoBuf.ProtoMember(3, Name = @"routes")]
        public global::System.Collections.Generic.List<TaskSequence> Routes { get; } = new global::System.Collections.Generic.List<TaskSequence>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(SolveType.Optimise)]
        public SolveType solveType
        {
            get { return __pbn__solveType ?? SolveType.Optimise; }
            set { __pbn__solveType = value; }
        }
        public bool ShouldSerializesolveType() => __pbn__solveType != null;
        public void ResetsolveType() => __pbn__solveType = null;
        private SolveType? __pbn__solveType;

        [global::ProtoBuf.ProtoContract()]
        public enum SolveType
        {
            Optimise = 0,
            Evaluate = 1,
            ReOptimise = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SolutionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"objective", IsRequired = true)]
        public float Objective { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"routes")]
        public global::System.Collections.Generic.List<Route> Routes { get; } = new global::System.Collections.Generic.List<Route>();

        [global::ProtoBuf.ProtoMember(3, Name = @"infeasibilities")]
        public global::System.Collections.Generic.List<Infeasibility> Infeasibilities { get; } = new global::System.Collections.Generic.List<Infeasibility>();

        [global::ProtoBuf.ProtoContract()]
        public partial class StopAttribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float startValue { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float endValue { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float slackValue { get; set; }

            [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
            public float slackCost { get; set; }

            [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
            public float tardyValue { get; set; }

            [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
            public float tardyCost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class InterStopAttribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float startValue { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float endValue { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Stop : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
            public int Id { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"sequence", IsRequired = true)]
            public int Sequence { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public string locationId { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public string taskId { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public string jobId { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"attributes")]
            public global::System.Collections.Generic.List<SolutionResponse.StopAttribute> Attributes { get; } = new global::System.Collections.Generic.List<SolutionResponse.StopAttribute>();

            [global::ProtoBuf.ProtoMember(7)]
            [global::System.ComponentModel.DefaultValue("")]
            public string compartmentId
            {
                get { return __pbn__compartmentId ?? ""; }
                set { __pbn__compartmentId = value; }
            }
            public bool ShouldSerializecompartmentId() => __pbn__compartmentId != null;
            public void ResetcompartmentId() => __pbn__compartmentId = null;
            private string __pbn__compartmentId;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class InterStop : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public int fromStopId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public int toStopId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
            public global::System.Collections.Generic.List<SolutionResponse.InterStopAttribute> Attributes { get; } = new global::System.Collections.Generic.List<SolutionResponse.InterStopAttribute>();

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<Geocode> routeSegments { get; } = new global::System.Collections.Generic.List<Geocode>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TransitRuleAttribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string ruleId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string dimId { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public int fromStopId { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public int toStopId { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float startValue { get; set; }

            [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
            public float endValue { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Route : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string vehicleId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"stops")]
            public global::System.Collections.Generic.List<SolutionResponse.Stop> Stops { get; } = new global::System.Collections.Generic.List<SolutionResponse.Stop>();

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<SolutionResponse.InterStop> interStops { get; } = new global::System.Collections.Generic.List<SolutionResponse.InterStop>();

            [global::ProtoBuf.ProtoMember(4, Name = @"fixedCost")]
            public float[] fixedCosts { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public global::System.Collections.Generic.List<SolutionResponse.TransitRuleAttribute> transitRuleAttributes { get; } = new global::System.Collections.Generic.List<SolutionResponse.TransitRuleAttribute>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Infeasibility : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string taskId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"infeasibilityInfo")]
            public global::System.Collections.Generic.List<Info> infeasibilityInfoes { get; } = new global::System.Collections.Generic.List<Info>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Info : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"message", IsRequired = true)]
                public string Message { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                [global::System.ComponentModel.DefaultValue("")]
                public string dimId
                {
                    get { return __pbn__dimId ?? ""; }
                    set { __pbn__dimId = value; }
                }
                public bool ShouldSerializedimId() => __pbn__dimId != null;
                public void ResetdimId() => __pbn__dimId = null;
                private string __pbn__dimId;

                [global::ProtoBuf.ProtoMember(3, Name = @"limit")]
                public float Limit
                {
                    get { return __pbn__Limit.GetValueOrDefault(); }
                    set { __pbn__Limit = value; }
                }
                public bool ShouldSerializeLimit() => __pbn__Limit != null;
                public void ResetLimit() => __pbn__Limit = null;
                private float? __pbn__Limit;

                [global::ProtoBuf.ProtoMember(4, Name = @"value")]
                public float Value
                {
                    get { return __pbn__Value.GetValueOrDefault(); }
                    set { __pbn__Value = value; }
                }
                public bool ShouldSerializeValue() => __pbn__Value != null;
                public void ResetValue() => __pbn__Value = null;
                private float? __pbn__Value;

                [global::ProtoBuf.ProtoMember(5, Name = @"count")]
                public long Count
                {
                    get { return __pbn__Count.GetValueOrDefault(); }
                    set { __pbn__Count = value; }
                }
                public bool ShouldSerializeCount() => __pbn__Count != null;
                public void ResetCount() => __pbn__Count = null;
                private long? __pbn__Count;

                [global::ProtoBuf.ProtoMember(6)]
                public global::System.Collections.Generic.List<string> constrainingTaskIds { get; } = new global::System.Collections.Generic.List<string>();

            }

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
