// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ivrdata-o43e0dvs78zq.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace IVRData
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TransitSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transits")]
        public global::System.Collections.Generic.List<TransitValue> Transits { get; } = new global::System.Collections.Generic.List<TransitValue>();

        [global::ProtoBuf.ProtoContract()]
        public partial class TransitValue : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string fromId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string toId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"value", IsRequired = true)]
            public float Value { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CachedTransitSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public TransitSet transitSet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CachedModel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"model", IsRequired = true)]
        public byte[] Model { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
