// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: matrix-vyv95n7wchpl.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Matrix
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Geocode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"longitude", IsRequired = true)]
        public float Longitude { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"latitude", IsRequired = true)]
        public float Latitude { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Location : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"geocode", IsRequired = true)]
        public Geocode Geocode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatrixRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"locations")]
        public global::System.Collections.Generic.List<Location> Locations { get; } = new global::System.Collections.Generic.List<Location>();

        [global::ProtoBuf.ProtoMember(2, Name = @"sources")]
        public global::System.Collections.Generic.List<string> Sources { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"destinations")]
        public global::System.Collections.Generic.List<string> Destinations { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public eDistanceUnit distanceUnit { get; set; } = eDistanceUnit.Kilometres;

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public eDurationUnit durationUnit { get; set; } = eDurationUnit.Minutes;

        [global::ProtoBuf.ProtoContract()]
        public enum eDurationUnit
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SECONDS")]
            Seconds = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MINUTES")]
            Minutes = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"HOURS")]
            Hours = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"DAYS")]
            Days = 3,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum eDistanceUnit
        {
            [global::ProtoBuf.ProtoEnum(Name = @"KILOMETRES")]
            Kilometres = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MILES")]
            Miles = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatrixResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"elements")]
        public global::System.Collections.Generic.List<Element> Elements { get; } = new global::System.Collections.Generic.List<Element>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Element : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string fromId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string toId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"distance", IsRequired = true)]
            public float Distance { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"duration", IsRequired = true)]
            public float Duration { get; set; }

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
