// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ns3-tbfvuwtge2iq.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Ns3
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Dimension : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Geocode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"longitude", IsRequired = true)]
        public float Longitude { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"latitude", IsRequired = true)]
        public float Latitude { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnitDimensionCost : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> dimensionIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2)]
        public float[] dimensionCoefficients { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float costPerUnit { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FixedDimensionCost : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> dimensionIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float fixedCost { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FlowDimensionalConstraint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> dimensionIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2)]
        public float[] dimensionCoefficients { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float flowMin { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float flowMax { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DimensionRange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string dimensionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float minRange { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float maxRange { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float flowPenalty { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Node : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"geocode", IsRequired = true)]
        public Geocode Geocode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"production")]
        public global::System.Collections.Generic.List<ProductFlow> Productions { get; } = new global::System.Collections.Generic.List<ProductFlow>();

        [global::ProtoBuf.ProtoMember(4, Name = @"consumption")]
        public global::System.Collections.Generic.List<ProductFlow> Consumptions { get; } = new global::System.Collections.Generic.List<ProductFlow>();

        [global::ProtoBuf.ProtoMember(5)]
        public Flow flow { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<ProductFlow> productFlows { get; } = new global::System.Collections.Generic.List<ProductFlow>();

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<string> allowableSources { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(8)]
        public int maximumSources
        {
            get { return __pbn__maximumSources.GetValueOrDefault(); }
            set { __pbn__maximumSources = value; }
        }
        public bool ShouldSerializemaximumSources() => __pbn__maximumSources != null;
        public void ResetmaximumSources() => __pbn__maximumSources = null;
        private int? __pbn__maximumSources;

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<string> allowableServiceClasses { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<FlowDimensionalConstraint> flowConstraints { get; } = new global::System.Collections.Generic.List<FlowDimensionalConstraint>();

        [global::ProtoBuf.ProtoContract()]
        public partial class ProductFlow : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
            public string Id { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<DimensionRange> dimensionRanges { get; } = new global::System.Collections.Generic.List<DimensionRange>();

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<FixedDimensionCost> FixedDimensionCosts { get; } = new global::System.Collections.Generic.List<FixedDimensionCost>();

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<UnitDimensionCost> unitDimensionCosts { get; } = new global::System.Collections.Generic.List<UnitDimensionCost>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Flow : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public global::System.Collections.Generic.List<DimensionRange> dimensionRanges { get; } = new global::System.Collections.Generic.List<DimensionRange>();

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<FixedDimensionCost> FixedDimensionCosts { get; } = new global::System.Collections.Generic.List<FixedDimensionCost>();

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<UnitDimensionCost> unitDimensionCosts { get; } = new global::System.Collections.Generic.List<UnitDimensionCost>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProductGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"product", IsRequired = true)]
        public string Product { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string productGroup { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"productSpecification")]
        public global::System.Collections.Generic.List<ProductSpecification> productSpecifications { get; } = new global::System.Collections.Generic.List<ProductSpecification>();

        [global::ProtoBuf.ProtoContract()]
        public partial class ProductSpecification : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string baseDimension { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"targetDimension")]
            public global::System.Collections.Generic.List<string> targetDimensions { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(3, Name = @"targetPerBase")]
            public float[] targetPerBases { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LaneRate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"source", IsRequired = true)]
        public string Source { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"destination", IsRequired = true)]
        public string Destination { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<string> productIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<string> productGroupIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<UnitDimensionCost> unitDimensionCosts { get; } = new global::System.Collections.Generic.List<UnitDimensionCost>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<FlowDimensionalConstraint> flowConstraints { get; } = new global::System.Collections.Generic.List<FlowDimensionalConstraint>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CostModel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"source", IsRequired = true)]
        public string Source { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<string> productGroupIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6, Name = @"unitDimensionCost")]
        public global::System.Collections.Generic.List<UnitDimensionCost> unitDimensionCosts { get; } = new global::System.Collections.Generic.List<UnitDimensionCost>();

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<FlowDimensionalConstraint> flowConstraints { get; } = new global::System.Collections.Generic.List<FlowDimensionalConstraint>();

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serviceClass
        {
            get { return __pbn__serviceClass ?? ""; }
            set { __pbn__serviceClass = value; }
        }
        public bool ShouldSerializeserviceClass() => __pbn__serviceClass != null;
        public void ResetserviceClass() => __pbn__serviceClass = null;
        private string __pbn__serviceClass;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Model : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dimensions")]
        public global::System.Collections.Generic.List<Dimension> Dimensions { get; } = new global::System.Collections.Generic.List<Dimension>();

        [global::ProtoBuf.ProtoMember(2, Name = @"nodes")]
        public global::System.Collections.Generic.List<Node> Nodes { get; } = new global::System.Collections.Generic.List<Node>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<LaneRate> laneRates { get; } = new global::System.Collections.Generic.List<LaneRate>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<CostModel> costModels { get; } = new global::System.Collections.Generic.List<CostModel>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<ProductGroup> productGroups { get; } = new global::System.Collections.Generic.List<ProductGroup>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SolveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"model")]
        public Model Model { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string modelID
        {
            get { return __pbn__modelID ?? ""; }
            set { __pbn__modelID = value; }
        }
        public bool ShouldSerializemodelID() => __pbn__modelID != null;
        public void ResetmodelID() => __pbn__modelID = null;
        private string __pbn__modelID;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(SolveType.Optimise)]
        public SolveType solveType
        {
            get { return __pbn__solveType ?? SolveType.Optimise; }
            set { __pbn__solveType = value; }
        }
        public bool ShouldSerializesolveType() => __pbn__solveType != null;
        public void ResetsolveType() => __pbn__solveType = null;
        private SolveType? __pbn__solveType;

        [global::ProtoBuf.ProtoContract()]
        public enum SolveType
        {
            Optimise = 0,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SolutionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"objective", IsRequired = true)]
        public float Objective { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float lowerBound
        {
            get { return __pbn__lowerBound.GetValueOrDefault(); }
            set { __pbn__lowerBound = value; }
        }
        public bool ShouldSerializelowerBound() => __pbn__lowerBound != null;
        public void ResetlowerBound() => __pbn__lowerBound = null;
        private float? __pbn__lowerBound;

        [global::ProtoBuf.ProtoMember(3)]
        public float optimalityGap
        {
            get { return __pbn__optimalityGap.GetValueOrDefault(); }
            set { __pbn__optimalityGap = value; }
        }
        public bool ShouldSerializeoptimalityGap() => __pbn__optimalityGap != null;
        public void ResetoptimalityGap() => __pbn__optimalityGap = null;
        private float? __pbn__optimalityGap;

        [global::ProtoBuf.ProtoMember(4, Name = @"assignments")]
        public global::System.Collections.Generic.List<Assignment> Assignments { get; } = new global::System.Collections.Generic.List<Assignment>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<NodeFlow> nodeFlows { get; } = new global::System.Collections.Generic.List<NodeFlow>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<NodeProductFlow> nodeProductFlows { get; } = new global::System.Collections.Generic.List<NodeProductFlow>();

        [global::ProtoBuf.ProtoMember(7, Name = @"geometryEdgeSummary")]
        public global::System.Collections.Generic.List<GeometryEdgeSummary> geometryEdgeSummaries { get; } = new global::System.Collections.Generic.List<GeometryEdgeSummary>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Assignment : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"source", IsRequired = true)]
            public string Source { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"destination", IsRequired = true)]
            public string Destination { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public string productId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"amount", IsRequired = true)]
            public float Amount { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            [global::System.ComponentModel.DefaultValue("")]
            public string laneRateId
            {
                get { return __pbn__laneRateId ?? ""; }
                set { __pbn__laneRateId = value; }
            }
            public bool ShouldSerializelaneRateId() => __pbn__laneRateId != null;
            public void ResetlaneRateId() => __pbn__laneRateId = null;
            private string __pbn__laneRateId;

            [global::ProtoBuf.ProtoMember(7)]
            [global::System.ComponentModel.DefaultValue("")]
            public string costModelId
            {
                get { return __pbn__costModelId ?? ""; }
                set { __pbn__costModelId = value; }
            }
            public bool ShouldSerializecostModelId() => __pbn__costModelId != null;
            public void ResetcostModelId() => __pbn__costModelId = null;
            private string __pbn__costModelId;

            [global::ProtoBuf.ProtoMember(8, Name = @"distance", IsRequired = true)]
            public float Distance { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"duration", IsRequired = true)]
            public float Duration { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"geometry")]
            public global::System.Collections.Generic.List<Geocode> Geometries { get; } = new global::System.Collections.Generic.List<Geocode>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class NodeProductFlow : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string nodeId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string productId { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float inFlow { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public float outFlow { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float flowCost { get; set; }

            [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
            public float fixedCost { get; set; }

            [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
            public float productionAmount { get; set; }

            [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
            public float productionPenalty { get; set; }

            [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
            public float productionCost { get; set; }

            [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
            public float consumptionAmount { get; set; }

            [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
            public float consumptionPenalty { get; set; }

            [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
            public float consumptionCost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class NodeFlow : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string nodeId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float inFlow { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float outFlow { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public float flowCost { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float fixedCost { get; set; }

            [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
            public float productFlowCost { get; set; }

            [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
            public float productFixedCost { get; set; }

            [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
            public float productionAmount { get; set; }

            [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
            public float productionPenalty { get; set; }

            [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
            public float productionCost { get; set; }

            [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
            public float consumptionAmount { get; set; }

            [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
            public float consumptionPenalty { get; set; }

            [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
            public float consumptionCost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class GeometryEdgeSummary : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"fxs")]
            public float[] Fxs { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"fys")]
            public float[] Fys { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"txs")]
            public float[] Txs { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"tys")]
            public float[] Tys { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"weights")]
            public float[] Weights { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"types")]
            public int[] Types { get; set; }

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
