// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: nvd-hap0j2y4zlm1.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Nvd
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Configuration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public eMeasurementUnit timeUnit { get; set; } = eMeasurementUnit.Minutes;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float timeCoef { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float timeCostCoef { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public eMeasurementUnit distanceUnit { get; set; } = eMeasurementUnit.Kilometres;

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public float distanceCostCoef { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public float intraTerritoryBalance { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public float interTerritoryBalance { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int weekLength { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int periodLength { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum eMeasurementUnit
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SECONDS")]
            Seconds = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MINUTES")]
            Minutes = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"HOURS")]
            Hours = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"DAYS")]
            Days = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"KILOMETRES")]
            Kilometres = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"MILES")]
            Miles = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Geocode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"longitude", IsRequired = true)]
        public float Longitude { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"latitude", IsRequired = true)]
        public float Latitude { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Profile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public eFrequency frequencyType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<customCycle> allowableCycles { get; } = new global::System.Collections.Generic.List<customCycle>();

        [global::ProtoBuf.ProtoMember(3)]
        public int numVisits
        {
            get { return __pbn__numVisits.GetValueOrDefault(); }
            set { __pbn__numVisits = value; }
        }
        public bool ShouldSerializenumVisits() => __pbn__numVisits != null;
        public void ResetnumVisits() => __pbn__numVisits = null;
        private int? __pbn__numVisits;

        [global::ProtoBuf.ProtoContract()]
        public partial class customCycle : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"visitProfile")]
            public bool[] visitProfiles { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum eFrequency
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CUSTOM")]
            Custom = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SEVEN_TIMES_A_WEEK")]
            SevenTimesAWeek = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SIX_TIMES_A_WEEK")]
            SixTimesAWeek = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"FIVE_TIMES_A_WEEK")]
            FiveTimesAWeek = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"FOUR_TIMES_A_WEEK")]
            FourTimesAWeek = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"THREE_TIMES_A_WEEK")]
            ThreeTimesAWeek = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"TWICE_A_WEEK")]
            TwiceAWeek = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"ONCE_A_WEEK")]
            OnceAWeek = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"EVERY_SECOND_WEEK")]
            EverySecondWeek = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"ONCE_A_MONTH")]
            OnceAMonth = 9,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Visit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location", IsRequired = true)]
        public Geocode Location { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float visitTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"profile", IsRequired = true)]
        public Profile Profile { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public TerritoryRelation territoryRelations { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class TerritoryRelation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Type type { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public global::System.Collections.Generic.List<string> territoryIds { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoContract()]
            public enum Type
            {
                [global::ProtoBuf.ProtoEnum(Name = @"INCLUSIVE")]
                Inclusive = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"EXCLUSIVE")]
                Exclusive = 1,
            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Territory : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dailyStartTime")]
        public float[] dailyStartTimes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dailyEndTime")]
        public float[] dailyEndTimes { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"location", IsRequired = true)]
        public Geocode Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VisitSequence : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string territoryId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int dayIndex { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"visitId")]
        public global::System.Collections.Generic.List<string> visitIds { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Model : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"configuration", IsRequired = true)]
        public Configuration Configuration { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"visits")]
        public global::System.Collections.Generic.List<Visit> Visits { get; } = new global::System.Collections.Generic.List<Visit>();

        [global::ProtoBuf.ProtoMember(3, Name = @"territories")]
        public global::System.Collections.Generic.List<Territory> Territories { get; } = new global::System.Collections.Generic.List<Territory>();

        [global::ProtoBuf.ProtoMember(4, Name = @"visitSequence")]
        public global::System.Collections.Generic.List<VisitSequence> visitSequences { get; } = new global::System.Collections.Generic.List<VisitSequence>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SolveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"model")]
        public Model Model { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string modelID
        {
            get { return __pbn__modelID ?? ""; }
            set { __pbn__modelID = value; }
        }
        public bool ShouldSerializemodelID() => __pbn__modelID != null;
        public void ResetmodelID() => __pbn__modelID = null;
        private string __pbn__modelID;

        [global::ProtoBuf.ProtoMember(3, Name = @"routes")]
        public global::System.Collections.Generic.List<VisitSequence> Routes { get; } = new global::System.Collections.Generic.List<VisitSequence>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(SolveType.Optimise)]
        public SolveType solveType
        {
            get { return __pbn__solveType ?? SolveType.Optimise; }
            set { __pbn__solveType = value; }
        }
        public bool ShouldSerializesolveType() => __pbn__solveType != null;
        public void ResetsolveType() => __pbn__solveType = null;
        private SolveType? __pbn__solveType;

        [global::ProtoBuf.ProtoContract()]
        public enum SolveType
        {
            Optimise = 0,
            Evaluate = 1,
            ReOptimise = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SolutionResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"frontier")]
        public global::System.Collections.Generic.List<CompactSolution> Frontiers { get; } = new global::System.Collections.Generic.List<CompactSolution>();

        [global::ProtoBuf.ProtoMember(2, Name = @"instance")]
        public SolutionInstance Instance { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class StopAttribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float startValue { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float endValue { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float slackValue { get; set; }

            [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
            public float slackCost { get; set; }

            [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
            public float tardyValue { get; set; }

            [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
            public float tardyCost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class InterStopAttribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string dimId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float startValue { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float endValue { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Stop : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
            public int Id { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"sequence", IsRequired = true)]
            public int Sequence { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public string locationId { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public string visitId { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"attributes")]
            public global::System.Collections.Generic.List<SolutionResponse.StopAttribute> Attributes { get; } = new global::System.Collections.Generic.List<SolutionResponse.StopAttribute>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class InterStop : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public int fromStopId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public int toStopId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
            public global::System.Collections.Generic.List<SolutionResponse.InterStopAttribute> Attributes { get; } = new global::System.Collections.Generic.List<SolutionResponse.InterStopAttribute>();

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<Geocode> routeSegments { get; } = new global::System.Collections.Generic.List<Geocode>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TransitRuleAttribute : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string ruleId { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string dimId { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public int fromStopId { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public int toStopId { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float startValue { get; set; }

            [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
            public float endValue { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"cost", IsRequired = true)]
            public float Cost { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Route : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string vehicleId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"stops")]
            public global::System.Collections.Generic.List<SolutionResponse.Stop> Stops { get; } = new global::System.Collections.Generic.List<SolutionResponse.Stop>();

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<SolutionResponse.InterStop> interStops { get; } = new global::System.Collections.Generic.List<SolutionResponse.InterStop>();

            [global::ProtoBuf.ProtoMember(4, Name = @"fixedCost")]
            public float[] fixedCosts { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public global::System.Collections.Generic.List<SummaryAttribute> summaryAttributes { get; } = new global::System.Collections.Generic.List<SummaryAttribute>();

            [global::ProtoBuf.ProtoMember(6)]
            public global::System.Collections.Generic.List<SolutionResponse.TransitRuleAttribute> transitRuleAttributes { get; } = new global::System.Collections.Generic.List<SolutionResponse.TransitRuleAttribute>();

            [global::ProtoBuf.ProtoMember(7, Name = @"day", IsRequired = true)]
            public int Day { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class SummaryAttribute : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
                public string dimId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"min", IsRequired = true)]
                public float Min { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"max", IsRequired = true)]
                public float Max { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"delta", IsRequired = true)]
                public float Delta { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Infeasibility : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public string taskId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"infeasibilityInfo")]
            public global::System.Collections.Generic.List<Info> infeasibilityInfoes { get; } = new global::System.Collections.Generic.List<Info>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Info : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"message", IsRequired = true)]
                public string Message { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                [global::System.ComponentModel.DefaultValue("")]
                public string dimId
                {
                    get { return __pbn__dimId ?? ""; }
                    set { __pbn__dimId = value; }
                }
                public bool ShouldSerializedimId() => __pbn__dimId != null;
                public void ResetdimId() => __pbn__dimId = null;
                private string __pbn__dimId;

                [global::ProtoBuf.ProtoMember(3, Name = @"limit")]
                public float Limit
                {
                    get { return __pbn__Limit.GetValueOrDefault(); }
                    set { __pbn__Limit = value; }
                }
                public bool ShouldSerializeLimit() => __pbn__Limit != null;
                public void ResetLimit() => __pbn__Limit = null;
                private float? __pbn__Limit;

                [global::ProtoBuf.ProtoMember(4, Name = @"value")]
                public float Value
                {
                    get { return __pbn__Value.GetValueOrDefault(); }
                    set { __pbn__Value = value; }
                }
                public bool ShouldSerializeValue() => __pbn__Value != null;
                public void ResetValue() => __pbn__Value = null;
                private float? __pbn__Value;

                [global::ProtoBuf.ProtoMember(5, Name = @"count")]
                public long Count
                {
                    get { return __pbn__Count.GetValueOrDefault(); }
                    set { __pbn__Count = value; }
                }
                public bool ShouldSerializeCount() => __pbn__Count != null;
                public void ResetCount() => __pbn__Count = null;
                private long? __pbn__Count;

                [global::ProtoBuf.ProtoMember(6)]
                public global::System.Collections.Generic.List<string> constrainingTaskIds { get; } = new global::System.Collections.Generic.List<string>();

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CompactSolution : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"visitSequence")]
            public global::System.Collections.Generic.List<VisitSequence> visitSequences { get; } = new global::System.Collections.Generic.List<VisitSequence>();

            [global::ProtoBuf.ProtoMember(2, Name = @"objectives")]
            public float[] Objectives { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<string> objectiveNames { get; } = new global::System.Collections.Generic.List<string>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SolutionInstance : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"routes")]
            public global::System.Collections.Generic.List<SolutionResponse.Route> Routes { get; } = new global::System.Collections.Generic.List<SolutionResponse.Route>();

            [global::ProtoBuf.ProtoMember(2, Name = @"infeasibilities")]
            public global::System.Collections.Generic.List<SolutionResponse.Infeasibility> Infeasibilities { get; } = new global::System.Collections.Generic.List<SolutionResponse.Infeasibility>();

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
