# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ivrdata-o43e0dvs78zq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ivrdata-o43e0dvs78zq.proto',
  package='IVRData',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1aivrdata-o43e0dvs78zq.proto\x12\x07IVRData\"}\n\nTransitSet\x12\x32\n\x08transits\x18\x01 \x03(\x0b\x32 .IVRData.TransitSet.TransitValue\x1a;\n\x0cTransitValue\x12\x0e\n\x06\x66romId\x18\x01 \x02(\t\x12\x0c\n\x04toId\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\x02\";\n\x10\x43\x61\x63hedTransitSet\x12\'\n\ntransitSet\x18\x01 \x02(\x0b\x32\x13.IVRData.TransitSet\"\x1c\n\x0b\x43\x61\x63hedModel\x12\r\n\x05model\x18\x01 \x02(\x0c')
)




_TRANSITSET_TRANSITVALUE = _descriptor.Descriptor(
  name='TransitValue',
  full_name='IVRData.TransitSet.TransitValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromId', full_name='IVRData.TransitSet.TransitValue.fromId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toId', full_name='IVRData.TransitSet.TransitValue.toId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='IVRData.TransitSet.TransitValue.value', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=164,
)

_TRANSITSET = _descriptor.Descriptor(
  name='TransitSet',
  full_name='IVRData.TransitSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transits', full_name='IVRData.TransitSet.transits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRANSITSET_TRANSITVALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=164,
)


_CACHEDTRANSITSET = _descriptor.Descriptor(
  name='CachedTransitSet',
  full_name='IVRData.CachedTransitSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transitSet', full_name='IVRData.CachedTransitSet.transitSet', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=225,
)


_CACHEDMODEL = _descriptor.Descriptor(
  name='CachedModel',
  full_name='IVRData.CachedModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='IVRData.CachedModel.model', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=255,
)

_TRANSITSET_TRANSITVALUE.containing_type = _TRANSITSET
_TRANSITSET.fields_by_name['transits'].message_type = _TRANSITSET_TRANSITVALUE
_CACHEDTRANSITSET.fields_by_name['transitSet'].message_type = _TRANSITSET
DESCRIPTOR.message_types_by_name['TransitSet'] = _TRANSITSET
DESCRIPTOR.message_types_by_name['CachedTransitSet'] = _CACHEDTRANSITSET
DESCRIPTOR.message_types_by_name['CachedModel'] = _CACHEDMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransitSet = _reflection.GeneratedProtocolMessageType('TransitSet', (_message.Message,), dict(

  TransitValue = _reflection.GeneratedProtocolMessageType('TransitValue', (_message.Message,), dict(
    DESCRIPTOR = _TRANSITSET_TRANSITVALUE,
    __module__ = 'ivrdata_o43e0dvs78zq_pb2'
    # @@protoc_insertion_point(class_scope:IVRData.TransitSet.TransitValue)
    ))
  ,
  DESCRIPTOR = _TRANSITSET,
  __module__ = 'ivrdata_o43e0dvs78zq_pb2'
  # @@protoc_insertion_point(class_scope:IVRData.TransitSet)
  ))
_sym_db.RegisterMessage(TransitSet)
_sym_db.RegisterMessage(TransitSet.TransitValue)

CachedTransitSet = _reflection.GeneratedProtocolMessageType('CachedTransitSet', (_message.Message,), dict(
  DESCRIPTOR = _CACHEDTRANSITSET,
  __module__ = 'ivrdata_o43e0dvs78zq_pb2'
  # @@protoc_insertion_point(class_scope:IVRData.CachedTransitSet)
  ))
_sym_db.RegisterMessage(CachedTransitSet)

CachedModel = _reflection.GeneratedProtocolMessageType('CachedModel', (_message.Message,), dict(
  DESCRIPTOR = _CACHEDMODEL,
  __module__ = 'ivrdata_o43e0dvs78zq_pb2'
  # @@protoc_insertion_point(class_scope:IVRData.CachedModel)
  ))
_sym_db.RegisterMessage(CachedModel)


# @@protoc_insertion_point(module_scope)
