# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix-vyv95n7wchpl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matrix-vyv95n7wchpl.proto',
  package='Matrix',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19matrix-vyv95n7wchpl.proto\x12\x06Matrix\".\n\x07Geocode\x12\x11\n\tlongitude\x18\x01 \x02(\x02\x12\x10\n\x08latitude\x18\x02 \x02(\x02\"8\n\x08Location\x12\n\n\x02id\x18\x01 \x02(\t\x12 \n\x07geocode\x18\x02 \x02(\x0b\x32\x0f.Matrix.Geocode\"\xd2\x02\n\rMatrixRequest\x12#\n\tlocations\x18\x01 \x03(\x0b\x32\x10.Matrix.Location\x12\x0f\n\x07sources\x18\x02 \x03(\t\x12\x14\n\x0c\x64\x65stinations\x18\x03 \x03(\t\x12\x45\n\x0c\x64istanceUnit\x18\x04 \x02(\x0e\x32#.Matrix.MatrixRequest.eDistanceUnit:\nKILOMETRES\x12\x42\n\x0c\x64urationUnit\x18\x05 \x02(\x0e\x32#.Matrix.MatrixRequest.eDurationUnit:\x07MINUTES\">\n\reDurationUnit\x12\x0b\n\x07SECONDS\x10\x00\x12\x0b\n\x07MINUTES\x10\x01\x12\t\n\x05HOURS\x10\x02\x12\x08\n\x04\x44\x41YS\x10\x03\"*\n\reDistanceUnit\x12\x0e\n\nKILOMETRES\x10\x00\x12\t\n\x05MILES\x10\x01\"\x8f\x01\n\x0eMatrixResponse\x12\x30\n\x08\x65lements\x18\x01 \x03(\x0b\x32\x1e.Matrix.MatrixResponse.Element\x1aK\n\x07\x45lement\x12\x0e\n\x06\x66romId\x18\x01 \x02(\t\x12\x0c\n\x04toId\x18\x02 \x02(\t\x12\x10\n\x08\x64istance\x18\x03 \x02(\x02\x12\x10\n\x08\x64uration\x18\x04 \x02(\x02')
)



_MATRIXREQUEST_EDURATIONUNIT = _descriptor.EnumDescriptor(
  name='eDurationUnit',
  full_name='Matrix.MatrixRequest.eDurationUnit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SECONDS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINUTES', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOURS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAYS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=376,
  serialized_end=438,
)
_sym_db.RegisterEnumDescriptor(_MATRIXREQUEST_EDURATIONUNIT)

_MATRIXREQUEST_EDISTANCEUNIT = _descriptor.EnumDescriptor(
  name='eDistanceUnit',
  full_name='Matrix.MatrixRequest.eDistanceUnit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KILOMETRES', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MILES', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=440,
  serialized_end=482,
)
_sym_db.RegisterEnumDescriptor(_MATRIXREQUEST_EDISTANCEUNIT)


_GEOCODE = _descriptor.Descriptor(
  name='Geocode',
  full_name='Matrix.Geocode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Matrix.Geocode.longitude', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Matrix.Geocode.latitude', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=83,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='Matrix.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Matrix.Location.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geocode', full_name='Matrix.Location.geocode', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=141,
)


_MATRIXREQUEST = _descriptor.Descriptor(
  name='MatrixRequest',
  full_name='Matrix.MatrixRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='Matrix.MatrixRequest.locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sources', full_name='Matrix.MatrixRequest.sources', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destinations', full_name='Matrix.MatrixRequest.destinations', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distanceUnit', full_name='Matrix.MatrixRequest.distanceUnit', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='durationUnit', full_name='Matrix.MatrixRequest.durationUnit', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MATRIXREQUEST_EDURATIONUNIT,
    _MATRIXREQUEST_EDISTANCEUNIT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=482,
)


_MATRIXRESPONSE_ELEMENT = _descriptor.Descriptor(
  name='Element',
  full_name='Matrix.MatrixResponse.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromId', full_name='Matrix.MatrixResponse.Element.fromId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toId', full_name='Matrix.MatrixResponse.Element.toId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='Matrix.MatrixResponse.Element.distance', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Matrix.MatrixResponse.Element.duration', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=628,
)

_MATRIXRESPONSE = _descriptor.Descriptor(
  name='MatrixResponse',
  full_name='Matrix.MatrixResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='Matrix.MatrixResponse.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MATRIXRESPONSE_ELEMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=628,
)

_LOCATION.fields_by_name['geocode'].message_type = _GEOCODE
_MATRIXREQUEST.fields_by_name['locations'].message_type = _LOCATION
_MATRIXREQUEST.fields_by_name['distanceUnit'].enum_type = _MATRIXREQUEST_EDISTANCEUNIT
_MATRIXREQUEST.fields_by_name['durationUnit'].enum_type = _MATRIXREQUEST_EDURATIONUNIT
_MATRIXREQUEST_EDURATIONUNIT.containing_type = _MATRIXREQUEST
_MATRIXREQUEST_EDISTANCEUNIT.containing_type = _MATRIXREQUEST
_MATRIXRESPONSE_ELEMENT.containing_type = _MATRIXRESPONSE
_MATRIXRESPONSE.fields_by_name['elements'].message_type = _MATRIXRESPONSE_ELEMENT
DESCRIPTOR.message_types_by_name['Geocode'] = _GEOCODE
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['MatrixRequest'] = _MATRIXREQUEST
DESCRIPTOR.message_types_by_name['MatrixResponse'] = _MATRIXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Geocode = _reflection.GeneratedProtocolMessageType('Geocode', (_message.Message,), dict(
  DESCRIPTOR = _GEOCODE,
  __module__ = 'matrix_vyv95n7wchpl_pb2'
  # @@protoc_insertion_point(class_scope:Matrix.Geocode)
  ))
_sym_db.RegisterMessage(Geocode)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'matrix_vyv95n7wchpl_pb2'
  # @@protoc_insertion_point(class_scope:Matrix.Location)
  ))
_sym_db.RegisterMessage(Location)

MatrixRequest = _reflection.GeneratedProtocolMessageType('MatrixRequest', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXREQUEST,
  __module__ = 'matrix_vyv95n7wchpl_pb2'
  # @@protoc_insertion_point(class_scope:Matrix.MatrixRequest)
  ))
_sym_db.RegisterMessage(MatrixRequest)

MatrixResponse = _reflection.GeneratedProtocolMessageType('MatrixResponse', (_message.Message,), dict(

  Element = _reflection.GeneratedProtocolMessageType('Element', (_message.Message,), dict(
    DESCRIPTOR = _MATRIXRESPONSE_ELEMENT,
    __module__ = 'matrix_vyv95n7wchpl_pb2'
    # @@protoc_insertion_point(class_scope:Matrix.MatrixResponse.Element)
    ))
  ,
  DESCRIPTOR = _MATRIXRESPONSE,
  __module__ = 'matrix_vyv95n7wchpl_pb2'
  # @@protoc_insertion_point(class_scope:Matrix.MatrixResponse)
  ))
_sym_db.RegisterMessage(MatrixResponse)
_sym_db.RegisterMessage(MatrixResponse.Element)


# @@protoc_insertion_point(module_scope)
