# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: problem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='problem.proto',
  package='problem',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rproblem.proto\x12\x07problem\"\x8c\x01\n\x0fProblemEnvelope\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x38\n\x07subType\x18\x02 \x02(\x0e\x32 .problem.ProblemEnvelope.SubType:\x05INPUT\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\" \n\x07SubType\x12\t\n\x05INPUT\x10\x00\x12\n\n\x06OUTPUT\x10\x01\"\xa3\x01\n\nSolverInfo\x12\x14\n\x0cunixDateTime\x18\x01 \x02(\x03\x12\x13\n\x0binfoMessage\x18\x02 \x02(\t\x12\x33\n\x04type\x18\x03 \x02(\x0e\x32%.problem.SolverInfo.SolverMessageType\"5\n\x11SolverMessageType\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\xaa\x01\n\x0eSolverResponse\x12!\n\x04logs\x18\x01 \x03(\x0b\x32\x13.problem.SolverInfo\x12\x31\n\x05state\x18\x02 \x02(\x0e\x32\".problem.SolverResponse.SolveState\x12\x10\n\x08solution\x18\x03 \x01(\x0c\"0\n\nSolveState\x12\x07\n\x03WIP\x10\x00\x12\r\n\tCOMPLETED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02')
)



_PROBLEMENVELOPE_SUBTYPE = _descriptor.EnumDescriptor(
  name='SubType',
  full_name='problem.ProblemEnvelope.SubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INPUT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=167,
)
_sym_db.RegisterEnumDescriptor(_PROBLEMENVELOPE_SUBTYPE)

_SOLVERINFO_SOLVERMESSAGETYPE = _descriptor.EnumDescriptor(
  name='SolverMessageType',
  full_name='problem.SolverInfo.SolverMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INFO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=280,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_SOLVERINFO_SOLVERMESSAGETYPE)

_SOLVERRESPONSE_SOLVESTATE = _descriptor.EnumDescriptor(
  name='SolveState',
  full_name='problem.SolverResponse.SolveState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=458,
  serialized_end=506,
)
_sym_db.RegisterEnumDescriptor(_SOLVERRESPONSE_SOLVESTATE)


_PROBLEMENVELOPE = _descriptor.Descriptor(
  name='ProblemEnvelope',
  full_name='problem.ProblemEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='problem.ProblemEnvelope.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subType', full_name='problem.ProblemEnvelope.subType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='problem.ProblemEnvelope.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROBLEMENVELOPE_SUBTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=167,
)


_SOLVERINFO = _descriptor.Descriptor(
  name='SolverInfo',
  full_name='problem.SolverInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unixDateTime', full_name='problem.SolverInfo.unixDateTime', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infoMessage', full_name='problem.SolverInfo.infoMessage', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='problem.SolverInfo.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOLVERINFO_SOLVERMESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=333,
)


_SOLVERRESPONSE = _descriptor.Descriptor(
  name='SolverResponse',
  full_name='problem.SolverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logs', full_name='problem.SolverResponse.logs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='problem.SolverResponse.state', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solution', full_name='problem.SolverResponse.solution', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOLVERRESPONSE_SOLVESTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=506,
)

_PROBLEMENVELOPE.fields_by_name['subType'].enum_type = _PROBLEMENVELOPE_SUBTYPE
_PROBLEMENVELOPE_SUBTYPE.containing_type = _PROBLEMENVELOPE
_SOLVERINFO.fields_by_name['type'].enum_type = _SOLVERINFO_SOLVERMESSAGETYPE
_SOLVERINFO_SOLVERMESSAGETYPE.containing_type = _SOLVERINFO
_SOLVERRESPONSE.fields_by_name['logs'].message_type = _SOLVERINFO
_SOLVERRESPONSE.fields_by_name['state'].enum_type = _SOLVERRESPONSE_SOLVESTATE
_SOLVERRESPONSE_SOLVESTATE.containing_type = _SOLVERRESPONSE
DESCRIPTOR.message_types_by_name['ProblemEnvelope'] = _PROBLEMENVELOPE
DESCRIPTOR.message_types_by_name['SolverInfo'] = _SOLVERINFO
DESCRIPTOR.message_types_by_name['SolverResponse'] = _SOLVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProblemEnvelope = _reflection.GeneratedProtocolMessageType('ProblemEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _PROBLEMENVELOPE,
  __module__ = 'problem_pb2'
  # @@protoc_insertion_point(class_scope:problem.ProblemEnvelope)
  ))
_sym_db.RegisterMessage(ProblemEnvelope)

SolverInfo = _reflection.GeneratedProtocolMessageType('SolverInfo', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERINFO,
  __module__ = 'problem_pb2'
  # @@protoc_insertion_point(class_scope:problem.SolverInfo)
  ))
_sym_db.RegisterMessage(SolverInfo)

SolverResponse = _reflection.GeneratedProtocolMessageType('SolverResponse', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERRESPONSE,
  __module__ = 'problem_pb2'
  # @@protoc_insertion_point(class_scope:problem.SolverResponse)
  ))
_sym_db.RegisterMessage(SolverResponse)


# @@protoc_insertion_point(module_scope)
