# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsp-mcvfz472gty6.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tsp-mcvfz472gty6.proto',
  package='TSP',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16tsp-mcvfz472gty6.proto\x12\x03TSP\"+\n\x07Geocode\x12\n\n\x02id\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\"\x9e\x01\n\x03TSP\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.TSP.Geocode\x12\x39\n\x0c\x64istancetype\x18\x02 \x01(\x0e\x32\x16.TSP.TSP.eDistanceType:\x0bRoadNetwork\">\n\reDistanceType\x12\x0f\n\x0bRoadNetwork\x10\x01\x12\r\n\tEuclidean\x10\x02\x12\r\n\tHaversine\x10\x03\"\xc2\x01\n\x0cSolveRequest\x12\x17\n\x05model\x18\x01 \x01(\x0b\x32\x08.TSP.TSP\x12\x0f\n\x07modelID\x18\x02 \x01(\t\x12\x15\n\rvisitSequence\x18\x03 \x03(\t\x12\x38\n\tsolveType\x18\x04 \x01(\x0e\x32\x1b.TSP.SolveRequest.SolveType:\x08Optimise\"7\n\tSolveType\x12\x0c\n\x08Optimise\x10\x00\x12\x0c\n\x08\x45valuate\x10\x01\x12\x0e\n\nReOptimise\x10\x02\"z\n\x04\x45\x64ge\x12\x0c\n\x04\x66rom\x18\x01 \x02(\t\x12\n\n\x02to\x18\x02 \x02(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12$\n\x08geometry\x18\x04 \x03(\x0b\x32\x12.TSP.Edge.Geometry\x1a \n\x08Geometry\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\":\n\x10SolutionResponse\x12\x0c\n\x04tour\x18\x01 \x03(\t\x12\x18\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\t.TSP.Edge')
)



_TSP_EDISTANCETYPE = _descriptor.EnumDescriptor(
  name='eDistanceType',
  full_name='TSP.TSP.eDistanceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RoadNetwork', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Euclidean', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Haversine', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=235,
)
_sym_db.RegisterEnumDescriptor(_TSP_EDISTANCETYPE)

_SOLVEREQUEST_SOLVETYPE = _descriptor.EnumDescriptor(
  name='SolveType',
  full_name='TSP.SolveRequest.SolveType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Optimise', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Evaluate', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReOptimise', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=377,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_SOLVEREQUEST_SOLVETYPE)


_GEOCODE = _descriptor.Descriptor(
  name='Geocode',
  full_name='TSP.Geocode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TSP.Geocode.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='TSP.Geocode.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='TSP.Geocode.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=74,
)


_TSP = _descriptor.Descriptor(
  name='TSP',
  full_name='TSP.TSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='TSP.TSP.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distancetype', full_name='TSP.TSP.distancetype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TSP_EDISTANCETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=235,
)


_SOLVEREQUEST = _descriptor.Descriptor(
  name='SolveRequest',
  full_name='TSP.SolveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='TSP.SolveRequest.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modelID', full_name='TSP.SolveRequest.modelID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visitSequence', full_name='TSP.SolveRequest.visitSequence', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solveType', full_name='TSP.SolveRequest.solveType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOLVEREQUEST_SOLVETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=432,
)


_EDGE_GEOMETRY = _descriptor.Descriptor(
  name='Geometry',
  full_name='TSP.Edge.Geometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='TSP.Edge.Geometry.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='TSP.Edge.Geometry.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=556,
)

_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='TSP.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='TSP.Edge.from', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='TSP.Edge.to', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='TSP.Edge.distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='TSP.Edge.geometry', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EDGE_GEOMETRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=556,
)


_SOLUTIONRESPONSE = _descriptor.Descriptor(
  name='SolutionResponse',
  full_name='TSP.SolutionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tour', full_name='TSP.SolutionResponse.tour', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='TSP.SolutionResponse.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=616,
)

_TSP.fields_by_name['points'].message_type = _GEOCODE
_TSP.fields_by_name['distancetype'].enum_type = _TSP_EDISTANCETYPE
_TSP_EDISTANCETYPE.containing_type = _TSP
_SOLVEREQUEST.fields_by_name['model'].message_type = _TSP
_SOLVEREQUEST.fields_by_name['solveType'].enum_type = _SOLVEREQUEST_SOLVETYPE
_SOLVEREQUEST_SOLVETYPE.containing_type = _SOLVEREQUEST
_EDGE_GEOMETRY.containing_type = _EDGE
_EDGE.fields_by_name['geometry'].message_type = _EDGE_GEOMETRY
_SOLUTIONRESPONSE.fields_by_name['edges'].message_type = _EDGE
DESCRIPTOR.message_types_by_name['Geocode'] = _GEOCODE
DESCRIPTOR.message_types_by_name['TSP'] = _TSP
DESCRIPTOR.message_types_by_name['SolveRequest'] = _SOLVEREQUEST
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['SolutionResponse'] = _SOLUTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Geocode = _reflection.GeneratedProtocolMessageType('Geocode', (_message.Message,), dict(
  DESCRIPTOR = _GEOCODE,
  __module__ = 'tsp_mcvfz472gty6_pb2'
  # @@protoc_insertion_point(class_scope:TSP.Geocode)
  ))
_sym_db.RegisterMessage(Geocode)

TSP = _reflection.GeneratedProtocolMessageType('TSP', (_message.Message,), dict(
  DESCRIPTOR = _TSP,
  __module__ = 'tsp_mcvfz472gty6_pb2'
  # @@protoc_insertion_point(class_scope:TSP.TSP)
  ))
_sym_db.RegisterMessage(TSP)

SolveRequest = _reflection.GeneratedProtocolMessageType('SolveRequest', (_message.Message,), dict(
  DESCRIPTOR = _SOLVEREQUEST,
  __module__ = 'tsp_mcvfz472gty6_pb2'
  # @@protoc_insertion_point(class_scope:TSP.SolveRequest)
  ))
_sym_db.RegisterMessage(SolveRequest)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), dict(

  Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), dict(
    DESCRIPTOR = _EDGE_GEOMETRY,
    __module__ = 'tsp_mcvfz472gty6_pb2'
    # @@protoc_insertion_point(class_scope:TSP.Edge.Geometry)
    ))
  ,
  DESCRIPTOR = _EDGE,
  __module__ = 'tsp_mcvfz472gty6_pb2'
  # @@protoc_insertion_point(class_scope:TSP.Edge)
  ))
_sym_db.RegisterMessage(Edge)
_sym_db.RegisterMessage(Edge.Geometry)

SolutionResponse = _reflection.GeneratedProtocolMessageType('SolutionResponse', (_message.Message,), dict(
  DESCRIPTOR = _SOLUTIONRESPONSE,
  __module__ = 'tsp_mcvfz472gty6_pb2'
  # @@protoc_insertion_point(class_scope:TSP.SolutionResponse)
  ))
_sym_db.RegisterMessage(SolutionResponse)


# @@protoc_insertion_point(module_scope)
