# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsptw-kcxbievqo879.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tsptw-kcxbievqo879.proto',
  package='TSPTW',
  serialized_pb=_b('\n\x18tsptw-kcxbievqo879.proto\x12\x05TSPTW\"S\n\x07Geocode\x12\n\n\x02id\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\x13\n\x0bwindowStart\x18\x04 \x01(\x02\x12\x11\n\twindowEnd\x18\x05 \x01(\x02\"\xa2\x01\n\x03TSP\x12\x1e\n\x06points\x18\x01 \x03(\x0b\x32\x0e.TSPTW.Geocode\x12;\n\x0c\x64istancetype\x18\x02 \x01(\x0e\x32\x18.TSPTW.TSP.eDistanceType:\x0bRoadNetwork\">\n\reDistanceType\x12\x0f\n\x0bRoadNetwork\x10\x01\x12\r\n\tEuclidean\x10\x02\x12\r\n\tHaversine\x10\x03\"\xc6\x01\n\x0cSolveRequest\x12\x19\n\x05model\x18\x01 \x01(\x0b\x32\n.TSPTW.TSP\x12\x0f\n\x07modelID\x18\x02 \x01(\t\x12\x15\n\rvisitSequence\x18\x03 \x03(\t\x12:\n\tsolveType\x18\x04 \x01(\x0e\x32\x1d.TSPTW.SolveRequest.SolveType:\x08Optimise\"7\n\tSolveType\x12\x0c\n\x08Optimise\x10\x00\x12\x0c\n\x08\x45valuate\x10\x01\x12\x0e\n\nReOptimise\x10\x02\"\x8a\x01\n\x04\x45\x64ge\x12\x0c\n\x04\x66rom\x18\x01 \x02(\t\x12\n\n\x02to\x18\x02 \x02(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12\x0c\n\x04time\x18\x04 \x01(\x02\x12&\n\x08geometry\x18\x05 \x03(\x0b\x32\x14.TSPTW.Edge.Geometry\x1a \n\x08Geometry\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"R\n\x10SolutionResponse\x12\x0c\n\x04tour\x18\x01 \x03(\t\x12\x1a\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x0b.TSPTW.Edge\x12\x14\n\x0c\x61rrivalTimes\x18\x03 \x03(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TSP_EDISTANCETYPE = _descriptor.EnumDescriptor(
  name='eDistanceType',
  full_name='TSPTW.TSP.eDistanceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RoadNetwork', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Euclidean', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Haversine', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=221,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_TSP_EDISTANCETYPE)

_SOLVEREQUEST_SOLVETYPE = _descriptor.EnumDescriptor(
  name='SolveType',
  full_name='TSPTW.SolveRequest.SolveType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Optimise', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Evaluate', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReOptimise', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=429,
  serialized_end=484,
)
_sym_db.RegisterEnumDescriptor(_SOLVEREQUEST_SOLVETYPE)


_GEOCODE = _descriptor.Descriptor(
  name='Geocode',
  full_name='TSPTW.Geocode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TSPTW.Geocode.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='TSPTW.Geocode.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='TSPTW.Geocode.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windowStart', full_name='TSPTW.Geocode.windowStart', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windowEnd', full_name='TSPTW.Geocode.windowEnd', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=118,
)


_TSP = _descriptor.Descriptor(
  name='TSP',
  full_name='TSPTW.TSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='TSPTW.TSP.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distancetype', full_name='TSPTW.TSP.distancetype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TSP_EDISTANCETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=283,
)


_SOLVEREQUEST = _descriptor.Descriptor(
  name='SolveRequest',
  full_name='TSPTW.SolveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='TSPTW.SolveRequest.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelID', full_name='TSPTW.SolveRequest.modelID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visitSequence', full_name='TSPTW.SolveRequest.visitSequence', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solveType', full_name='TSPTW.SolveRequest.solveType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOLVEREQUEST_SOLVETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=484,
)


_EDGE_GEOMETRY = _descriptor.Descriptor(
  name='Geometry',
  full_name='TSPTW.Edge.Geometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='TSPTW.Edge.Geometry.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='TSPTW.Edge.Geometry.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=625,
)

_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='TSPTW.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='TSPTW.Edge.from', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='TSPTW.Edge.to', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='TSPTW.Edge.distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='TSPTW.Edge.time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='TSPTW.Edge.geometry', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EDGE_GEOMETRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=625,
)


_SOLUTIONRESPONSE = _descriptor.Descriptor(
  name='SolutionResponse',
  full_name='TSPTW.SolutionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tour', full_name='TSPTW.SolutionResponse.tour', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edges', full_name='TSPTW.SolutionResponse.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arrivalTimes', full_name='TSPTW.SolutionResponse.arrivalTimes', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=627,
  serialized_end=709,
)

_TSP.fields_by_name['points'].message_type = _GEOCODE
_TSP.fields_by_name['distancetype'].enum_type = _TSP_EDISTANCETYPE
_TSP_EDISTANCETYPE.containing_type = _TSP
_SOLVEREQUEST.fields_by_name['model'].message_type = _TSP
_SOLVEREQUEST.fields_by_name['solveType'].enum_type = _SOLVEREQUEST_SOLVETYPE
_SOLVEREQUEST_SOLVETYPE.containing_type = _SOLVEREQUEST
_EDGE_GEOMETRY.containing_type = _EDGE
_EDGE.fields_by_name['geometry'].message_type = _EDGE_GEOMETRY
_SOLUTIONRESPONSE.fields_by_name['edges'].message_type = _EDGE
DESCRIPTOR.message_types_by_name['Geocode'] = _GEOCODE
DESCRIPTOR.message_types_by_name['TSP'] = _TSP
DESCRIPTOR.message_types_by_name['SolveRequest'] = _SOLVEREQUEST
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['SolutionResponse'] = _SOLUTIONRESPONSE

Geocode = _reflection.GeneratedProtocolMessageType('Geocode', (_message.Message,), dict(
  DESCRIPTOR = _GEOCODE,
  __module__ = 'tsptw_kcxbievqo879_pb2'
  # @@protoc_insertion_point(class_scope:TSPTW.Geocode)
  ))
_sym_db.RegisterMessage(Geocode)

TSP = _reflection.GeneratedProtocolMessageType('TSP', (_message.Message,), dict(
  DESCRIPTOR = _TSP,
  __module__ = 'tsptw_kcxbievqo879_pb2'
  # @@protoc_insertion_point(class_scope:TSPTW.TSP)
  ))
_sym_db.RegisterMessage(TSP)

SolveRequest = _reflection.GeneratedProtocolMessageType('SolveRequest', (_message.Message,), dict(
  DESCRIPTOR = _SOLVEREQUEST,
  __module__ = 'tsptw_kcxbievqo879_pb2'
  # @@protoc_insertion_point(class_scope:TSPTW.SolveRequest)
  ))
_sym_db.RegisterMessage(SolveRequest)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), dict(

  Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), dict(
    DESCRIPTOR = _EDGE_GEOMETRY,
    __module__ = 'tsptw_kcxbievqo879_pb2'
    # @@protoc_insertion_point(class_scope:TSPTW.Edge.Geometry)
    ))
  ,
  DESCRIPTOR = _EDGE,
  __module__ = 'tsptw_kcxbievqo879_pb2'
  # @@protoc_insertion_point(class_scope:TSPTW.Edge)
  ))
_sym_db.RegisterMessage(Edge)
_sym_db.RegisterMessage(Edge.Geometry)

SolutionResponse = _reflection.GeneratedProtocolMessageType('SolutionResponse', (_message.Message,), dict(
  DESCRIPTOR = _SOLUTIONRESPONSE,
  __module__ = 'tsptw_kcxbievqo879_pb2'
  # @@protoc_insertion_point(class_scope:TSPTW.SolutionResponse)
  ))
_sym_db.RegisterMessage(SolutionResponse)


# @@protoc_insertion_point(module_scope)
